version: '3.9'

services:

  db:
    image: postgres:14.7-alpine
    container_name: db
    restart: always
    env_file: '.env'
    ports:
      - 5432:5432

  flowbuild:
    image: flowbuild/server:latest
    container_name: flowbuild
    restart: on-failure:10
    env_file: '.env'
    depends_on: 
      - db
      - mqtt
    ports:
      - 3000:3000
    command: bash -c " npm run migrations && npm run seeds && npm run start "

  mqtt:
    image: hivemq/hivemq4:latest
    container_name: mqtt
    ports:
      - 8080:8080
      - 1883:1883
      - 8000:8000

  studio:
    image: flowbuild/studio:0.1.0-compose
    container_name: studio
    ports:
      - 3000:80

  redis:
    image: redis:7-bullseye
    container_name: redis_queue
    restart: always
    ports: 
      - 6379:6379
  
  timer:
    image: flowbuild/timer-worker:1.0.0-development.1
    container_name: timer
    restart: on-failure:10
    env_file: '.env'
    depends_on: 
      - redis
    ports:
      - 3001:3001
    command: bash -c " npm run migrations && npm run seeds && npm run start "